---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.76.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      valuesKey: client-id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth
      valuesKey: client-secret
      targetPath: oauth.clientSecret
  values:
    operatorConfig:
      hostname: oci-k8s-operator
      logging: info
